# Generated by Django 5.2.7 on 2025-11-02 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_depositrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền rút')),
                ('full_name_cccd', models.CharField(max_length=100, verbose_name='Tên trên CCCD (Người nhận)')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Tên ngân hàng')),
                ('account_number', models.CharField(max_length=50, verbose_name='Số tài khoản')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ xử lý'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Đã từ chối')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Ngày admin xử lý', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
