# Generated by Django 5.2.7 on 2025-11-01 15:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('DE', 'Đề (2 số cuối GĐB)'), ('LO', 'Lô (2 số cuối 27 giải)')], max_length=2)),
                ('number', models.CharField(help_text='Số cược (ví dụ: 86, 23)', max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(help_text='Cược cho ngày')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('WON', 'Thắng'), ('LOST', 'Thua')], default='PENDING', max_length=10)),
                ('winnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LotteryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Ngày mở thưởng', unique=True)),
                ('prizes', models.JSONField(help_text='Danh sách 27 giải, từ GĐB đến giải 7. Ví dụ: ["54321", "12345", ...]')),
                ('de_number', models.CharField(blank=True, help_text='2 số cuối giải đặc biệt (tự động cập nhật)', max_length=2)),
                ('lo_numbers', models.JSONField(blank=True, help_text='Danh sách 27 số lô (tự động cập nhật)', null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
