# Generated by Django 5.2.7 on 2025-11-09 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên đài')),
                ('identifier', models.SlugField(help_text='Ví dụ: mien-bac, tp-hcm, long-an', max_length=100, unique=True)),
                ('region', models.CharField(choices=[('NORTH', 'Miền Bắc'), ('SOUTH', 'Miền Nam'), ('CENTRAL', 'Miền Trung')], default='NORTH', max_length=10, verbose_name='Vùng miền')),
                ('prize_count', models.PositiveIntegerField(default=27, verbose_name='Số lượng giải (MB=27, MN/MT=18)')),
                ('cutoff_hour', models.PositiveIntegerField(default=18, help_text='Giờ chốt cược (ví dụ: 18 cho 18h00)')),
                ('schedule_days', models.CharField(default='ALL', help_text="Các thứ quay (0=T2, 6=CN) cách nhau bằng dấu phẩy, hoặc 'ALL' cho 7 ngày", max_length=50)),
            ],
            options={
                'verbose_name': 'Đài quay thưởng',
                'verbose_name_plural': 'Các đài quay thưởng',
            },
        ),
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vé cược', 'verbose_name_plural': 'Các vé cược'},
        ),
        migrations.AlterModelOptions(
            name='lotteryresult',
            options={'ordering': ['-date', 'station'], 'verbose_name': 'Kết quả xổ số', 'verbose_name_plural': 'Các kết quả xổ số'},
        ),
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền cược'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('DE', 'Đề (2 số cuối GĐB)'), ('LO', 'Lô (2 số cuối các giải)')], max_length=10, verbose_name='Loại cược'),
        ),
        migrations.AlterField(
            model_name='lotteryresult',
            name='date',
            field=models.DateField(help_text='Ngày mở thưởng'),
        ),
        migrations.AlterField(
            model_name='lotteryresult',
            name='de_number',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='lotteryresult',
            name='lo_numbers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lotteryresult',
            name='prizes',
            field=models.JSONField(help_text='Danh sách các giải'),
        ),
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bet',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='lottery.lotterystation', verbose_name='Đài'),
        ),
        migrations.AddField(
            model_name='lotteryresult',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lottery.lotterystation', verbose_name='Đài'),
        ),
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together={('user', 'bet_type', 'number', 'date', 'station')},
        ),
        migrations.AlterUniqueTogether(
            name='lotteryresult',
            unique_together={('date', 'station')},
        ),
    ]
